- name: Remove virtual machine from vSphere
  gather_facts: no
  hosts: localhost
  tasks:
  - name: Remove "{{ vm_name }}"
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      cluster: "{{ cluster_name }}"
      name: "{{ vm_name }}"
      state: absent
    delegate_to: localhost
    register: facts