--- # MODULE EC2_AMI_COPY EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files: 
  - files/awscreds.yml
  tasks:
  - name: Copy AMI from one region to another
    ec2_ami_copy:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      source_region: "{{ aws_region }}"
      source_image_id: ami-91b6aff0
      wait: no
      name: useastami1
      tags: 
        Name: MyNewEastAMI1
        Service: TestEastAMIService1
    register: instance

